# Generated by Django 5.1.6 on 2025-02-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=25, verbose_name='Last Name')),
                ('middlename', models.CharField(blank=True, max_length=25, null=True, verbose_name='Middle Name')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
