# Generated by Django 5.2 on 2025-04-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_user_availability_user_role_user_skill_level_court_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
