# Generated by Django 5.2.6 on 2025-09-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
